### ISSUE TITLE
Total freeze with bios v321 after 10 min

### ISSUE THREAD

**Issue by toxin265** [Baio1977/Asus-ROG-GL703ge#2]
Only the power button helps me ... (
What could be the reason? Where can I find a log?
The hackintosh is still new to me.

**Comment by Baio1977** [comment]
[EFI Debug 0.7.5.zip](https://github.com/Baio1977/Asus-ROG-GL703ge-/files/7822095/EFI.Debug.0.7.5.zip)
extract new file Bios V321 ,insert EFI debug in USB

**Comment by toxin265** [comment]
Hi,
I inserted your EFI debugger to my empty EFI partition.
My debugged efi in the attachment
[gl703ge-bios-v321-debug-dumped.EFI.zip](https://github.com/Baio1977/Asus-ROG-GL703ge-/files/7829905/gl703ge-bios-v321-debug-dumped.EFI.zip)
.

**Comment by Baio1977** [comment]
https://github.com/Baio1977/Asus-ROG-GL703ge-/releases/tag/V2 test this ioreg if start

**Comment by Lorys89** [comment]
solved. closed the issue.
